### ISSUE TITLE
Compilation error generating constants SRS_UL

### ISSUE THREAD

**Issue by inkstak** [telus-agcg/ffi-gdal#74]
Hi, I've tried to install this gem in replacement of [gdal](https://rubygems.org/gems/gdal) gem and I've got the following error:

```ruby
require "gdal"
GDAL::Driver

# [...]/gems/ffi-1.15.5/lib/ffi/tools/const_generator.rb:133:in `block in calculate': Compilation error generating constants SRS_UL: # (RuntimeError)
#	/var/folders/yg/3y5g9r6n2s58vht8yvdyv7480000gn/T/SRS_UL.const_generator20230828-74680-513c7o:3:10: error: # empty filename
# 	#include <>
#	         ^
#	1 error generated.
```

gdal 3.6.2 is installed through homebrew, on a MacOS Ventura.

Any thoughts ?

**Comment by turboladen** [comment]
I'm on the same OS with GDAL 3.7.1 via homebrew and get this as well. Initially, I'm tempted to say this could fall under #11 (no official 3.x support yet; I know, it's sorely out of date), but this seems fixable as a standalone issue (I wonder if there was a change in the homebrew packaging?).

**Comment by turboladen** [comment]
Fixed in gh-105.
